language: minimal
os: linux
env:
  - VERSION=$TRAVIS_BUILD_NUMBER

stages:
  - name: stage1
    if: branch =~ /^prep/ AND type = push
  - name: stage2
    if: env(COCOAPODS) = true

jobs:
  include:
    - stage: stage1
      name: this is stage 1
      language: objective-c
      os: osx
      install:
        - brew install hub
      script:
        - ./run_prep.sh

    - stage: stage2
      name: this is stage 2
      language: minimal
      os: linux
      script:
        - ./run_release.sh
