language: objective-c
env:
  TARGET=optimizely/objective-c-sdk
install:
  - mkdir -p $HOME/$TARGET && pushd $HOME/$TARGET && git init && git pull https://github.com/$TARGET && popd
script:
  - cd $HOME/$TARGET
  - xcrun agvtool what-marketing-version
  - xcrun agvtool what-version
