language: cpp
# Only Windows Server, version 1803 is currently supported.
os: windows
script:
  - echo $TRAVIS_OS_NAME
  # https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
  - ver
  - docker version
