language: minimal
os: linux

stages:
  - name: stage1
    if: branch =~ /^prep/ AND type = push
  - name: stage2
    if: env(RELEASE) = true

jobs:
  include:
    - stage: stage1
      name: this is stage 1
      language: objective-c
      os: osx
      env:
        - VERSION=$TRAVIS_BUILD_NUMBER
      install:
        - brew install hub
      script:
        - ./runme.sh

    - stage: stage2
      name: this is stage 2
      language: minimal
      os: linux
      script:
        - echo "doing stage 2 things"
