language: minimal
os: linux

env:
  global:
    - HELLO=hello
    - BASED_ON_HELLO=blah/blah$HELLO
    - COLOR_RESET='\e[0m'
    - COLOR_RED='\e[31m'
script:
  - echo "${COLOR_RED}blah $BASED_ON_HELLO ${COLOR_RESET} lkjsdf"
  - pwd
  - cd $HOME
  - mkdir test
  - cd test
  - pwd
