language: minimal
os: linux

stages:
  - name: stage1
    if: branch =~ /^prep/ AND type = pull_request
  - name: stage2
    if: branch = master AND type = push AND env(RELEASE) = true

jobs:
  include:
    - stage: stage1
      name: this is stage 1
      language: objective-c
      os: osx
      env:
        global:
          - VERSION=1.0.1
          - COLOR_RESET='\033[0m'
          - COLOR_MAGENTA='\033[0;35m'
          - COLOR_CYAN='\033[0;36m'
          - MYREPO=$HOME/$TRAVIS_REPO_SLUG
          - AUTOBRANCH=testing/mybranch$VERSION
      install:
        - brew install hub
      script:
        - mkdir $MYREPO
        - git clone https://$CI_USER_TOKEN@github.com/$TRAVIS_REPO_SLUG $MYREPO
        - cd $MYREPO
        - git checkout -b $AUTOBRANCH
        - echo "test $VERSION" >> version
        - git commit -a
        - git push https://$CI_USER_TOKEN@github.com/$TRAVIS_REPO_SLUG $AUTOBRANCH
        - PR_URL=$(hub pull-request --no-edit) && echo "${COLOR_CYAN}ATTENTION:${COLOR_RESET} review and merge ${PR_URL} to continue..."

    - stage: stage2
      name: this is stage 2
      language: minimal
      os: linux
      script:
        - echo "doing stage 2 things"
