language: cpp
# Only Windows Server, version 1803 is currently supported.
os: windows
script:
  - echo $TRAVIS_OS_NAME
  - docker version
  - docker pull alpine
    #  - docker pull mcr.microsoft.com/windows/servercore:1803
