language: cpp
# Only Windows Server, version 1803 is currently supported.
os: windows
script:
  - echo $TRAVIS_OS_NAME
  - docker version
  - docker build .
    #  - docker pull microsoft/windowsservercore:1803
